server:
 contextPath: /api/v1/autocompletecities
 port: 8080


api: 
 program:
  name: Autocomplete Cities Service
 version: v1
 
file:
 path: src/main/resources/CityList.csv
 
#file:
# path: src/main/resources/All_India_pincode_data_26022018.csv

city:
 list:
  index: 0